In [1]:
import numpy as np
import pandas as pd

In [4]:
x_mean = np.array([1,1,1])
x_cov = np.array([[0.8,1.4,0.4],
                 [1.0,0.6,0.7],
                 [1.2,0.3,0.2]])
class1_sample = np.random.multivariate_normal(x_mean,x_cov, 20)
df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1

x2_mean = np.array([2,3,2])
class2_sample = np.random.multivariate_normal(x2_mean , x_cov, 20)
df1 = pd.DataFrame(class2_sample ,columns= ['feature1', 'feature2', 'feature3'])
df1['target'] = 0

df = pd.concat([df, df1], ignore_index=True)
df.sample(5)

/var/folders/cl/nx895lk15wz0q6n08sgg8vtr0000gn/T/ipykernel_69730/3403236554.py:5: RuntimeWarning: covariance is not symmetric positive-semidefinite.
  class1_sample = np.random.multivariate_normal(x_mean,x_cov, 20)
/var/folders/cl/nx895lk15wz0q6n08sgg8vtr0000gn/T/ipykernel_69730/3403236554.py:10: RuntimeWarning: covariance is not symmetric positive-semidefinite.
  class2_sample = np.random.multivariate_normal(x2_mean , x_cov, 20)


feature1  feature2  feature3  target
23  0.282477  2.668798  0.358986       0
29  2.163761  4.715037  2.624304       0
2   2.137747  0.809744  0.868158       1
8   2.736758  3.250220  2.323793       1
28  1.067649  2.614137  1.546259       0

In [6]:
import plotly.express as px
#y_train_trf = y_train.astype(str)
fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
              color=df['target'].astype('str'))


fig.show()
     

In [7]:
# Step 1 - Apply standard scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [9]:
# Step 2 - Find Covariance Matrix
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[1.02564103 0.33243121 0.4706694 ]
 [0.33243121 1.02564103 0.34355667]
 [0.4706694  0.34355667 1.02564103]]


In [10]:
# Step 3 - Finding EV and EVs
eigen_value, eigen_vector = np.linalg.eig(covariance_matrix)
eigen_value

array([1.7937769 , 0.55470053, 0.72844565])

In [11]:
eigen_vector

array([[-0.59797129, -0.69421915,  0.40061216],
       [-0.52835906, -0.034434  , -0.84832246],
       [-0.60271638,  0.71893954,  0.34620644]])

In [17]:
pc = eigen_vector[0:2]
pc

array([[-0.59797129, -0.69421915,  0.40061216],
       [-0.52835906, -0.034434  , -0.84832246]])

In [18]:
transformed_df = np.dot(df.iloc[:,0:3], pc.T)
transformed_df = pd.DataFrame(transformed_df,columns= ['PC1', 'PC2'])
transformed_df['target'] = df['target'].values
transformed_df.head()

PC1       PC2  target
0 -1.001035  1.040458       1
1  0.985251  2.169908       1
2 -0.045768  0.414523       1
3  0.301875  1.286849       1
4 -0.111819 -1.621811       1

In [28]:
transformed_df['target'] = transformed_df['target'].astype('str')
fig = px.scatter(x=transformed_df['PC1'],
                 y=transformed_df['PC2'],
                 color=transformed_df['target'],
                 
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='black')),
                  selector=dict(mode='markers'))
fig.show()
     